<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Contact;
use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function contacts($owner)
    {
        $recs = $this->findBy(['owner' => $owner]);
        $ret = [];

        foreach ($recs as $rec) {
            /** @var Contact $rec */
            $ret[] = $rec->contact();
        }

        return $ret;
    }
}
